name: CI – Construcción y publicación App SpringBoot

on:
  push:
    branches: [principal]
  pull_request:
    branches: [principal]

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  compilar_y_publicar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Establecer variables
        run: |
          echo "IMAGE=${{ env.REGISTRY }}/${{ github.repository_owner }}/miapp" >> $GITHUB_ENV
          echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_ENV

      - name: Construir y enviar imagen (Dockerfile de varias etapas)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE }}:latest
